language: python
python:
  - '3.6'
install:
  - pip install pipenv
  - pipenv sync
  - pipenv sync --dev
script:
  - pylama
  - pytest --cov=. --cov-report=xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
